# Fiddle::Pointer is the raw-FFI escape hatch: access is unchecked against the
# recorded size, exactly like CRuby. p[0, 20] on an 8-byte buffer reads 20 raw
# bytes; #size reports the malloc size; #to_str reads exactly size bytes while
# #to_s stops at the first NUL. This test pins that CRuby-faithful behavior
# (the .expected is generated by ruby).
require "fiddle"

p = Fiddle::Pointer.malloc(8)
p[0, 5] = "hello"

puts p.size                 # 8 (recorded malloc size)
puts p.null?                # false
puts p[0, 5]                # hello
puts p.to_s                 # hello (NUL-stops at byte 5)
puts p.to_str.bytesize      # 8 (exactly size bytes, NULs included)
puts p[0, 20].bytesize      # 20 -- unchecked read past size, like CRuby

# a wrapped NULL pointer reports size 0 and null?
puts Fiddle::NULL.null?     # true
puts Fiddle::NULL.size      # 0

p.free
